# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "ehci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      kernelModules = [ ];
    };
    # kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
    kernelParams = [
      "console=ttyS0,115200"
      "console=tty1"
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/153c22fe-4fc4-453f-8368-bc4445eaaaf5";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AEA2-4DED";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f8cf1d1c-eb30-46e7-8815-a27d16afdb55"; }
  ];

}
